import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav style={{ 
          padding: '1rem 2rem', 
          borderBottom: '1px solid #e5e5e5',
          display: 'flex',
          gap: '2rem'
        }}>
          <Link href="/" style={{ textDecoration: 'none', color: '#333' }}>홈</Link>
          <Link href="/tool-settings" style={{ textDecoration: 'none', color: '#333' }}>도구 설정</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
